### ISSUE TITLE
this model confidence very low on network photo

### ISSUE THREAD

**Issue by einsitang** [thawro/yolov8-digits-detection#3]
is this model only detect on handwriting ?
because I try picture from network with print font ,the digits detect confidence is very low.

![image](https://github.com/user-attachments/assets/f11effe2-7509-4e61-be39-c5972a1d6ab1)

kaggle : https://www.kaggle.com/code/jianbintangelement/number-detect

**Comment by thawro** [comment]
Hello @einsitang 
The model used in the [demo](https://thawro.github.io/web-object-detector/) was trained with the **H**and**W**ritten **D**igits ([HWD+](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9702948/)) dataset (actually with the strongly augmented version, described [here](https://github.com/thawro/yolov8-digits-detection?tab=readme-ov-file#yolo_hwd)), which contains only digits written by hand, thus it may work poor on digital digits ("print font"). If you need the model to work on the digitcal digits too, I would suggest to extend the dataset with that type of data and retrain the network. 

The training is done with the [ultralytics](https://github.com/ultralytics) package, so you would only need to add images of the digits to specific directories (`datasets/yolo_HWD+/images/train` and `datasets/yolo_HWD+/images/test` paths, as defined in [config](https://github.com/thawro/yolov8-digits-detection/blob/main/yolo_HWD%2B.yaml)) and run the [train script](https://github.com/thawro/yolov8-digits-detection/blob/main/src/train.py).

To prepare the HWD+ data (needed for the training):
1. Download HWD+ dataset and place it in `datasets/HWD+` directory
2. Run
```bash
python src/data/split_HWD+.py
python src/data/generate_yolo_dataset.py
```

NOTE: Please change the [line](https://github.com/thawro/yolov8-digits-detection/blob/b73467a263f95a47cba9fcc45d381144fb5c88bb/src/data/generate_yolo_dataset.py#L308) to `all_images_filepaths = np.array(glob.glob(str(old_ds_path / "images/*/*")))` (in order to iterate over randomly selected train and val HWD+ splits)

**Comment by einsitang** [comment]
Thank you very much.I originally hoped that I could quickly find a model to process the recognition of these two items at the same time. Although I did not find it directly, the appropriate data set and the effect of the pre-model can already meet the requirements of my self-training model

**Comment by thawro** [comment]
Glad I could help :) 

If you have any more questions or run into any other issues, just give me a shout. Also, if everything's good now, you can go ahead and close this issue.

Thanks!
